### ISSUE TITLE
Not all embedded image are displayed, depending by different sources

### ISSUE THREAD

**Issue by leorac** [slurdge/goeland#2] opened 2020-12-02 08:40 UTC
Using source as 

```
[sources.calcio]
url = "https://www.corrieredellosport.it/rss/calcio"
type = "feed"
filters = ["unseen","includelink","embedimage","digest"]
```
The email works fine, displaying the embedded image. 

If I use this resource:
```
[sources.focus_scienza]
url = "https://www.focus.it/rss/scienza.rss"
type = "feed"
filters = ["unseen","includelink","embedimage","digest"]
```
The email doesn't display the image, showing a blank line space instead. The tag in the RSS is the same, called **Enclosure**. My Rss client (Vienna) displays both of them. It would be great if I didn't have to specify "embedimage" as filter, but the image would be displayed by default, as normally an RSS client does.

**Comment by slurdge** [comment] 2020-12-05 10:21
Thanks for the report! I'll take a look at the other source and as to why the image is not displayed.

As for the embedimage, I also would like it by default, but some people prefer to control if a picture is embedded or not. A solution would be to create "meta-filters" (in the binary) that would take most useful filters (like the one you have above)

**Comment by slurdge** [comment] 2020-12-12 15:36
Sorry for the delay.
Please try v0.6.1 which should fetch more images.
The cause was that the `https://www.focus.it/rss/scienza.rss` has a different way to embed images.

**Comment by leorac** [comment] 2020-12-12 17:49
Thank You, it works nice now! Thank you for writing this amazing software! Stay well and be safe!

**Comment by slurdge** [comment] 2020-12-12 21:28
Nice! Let's close it.

**Closed by slurdge** 2020-12-12 21:28 UTC
