### ISSUE TITLE
Digest of two RSS feeds not getting articles

### ISSUE THREAD

**Issue by djm1** [slurdge/goeland#41] opened 2022-06-06 18:03 UTC
**Describe the bug**
I have two RSS feeds, from which the RSS digest is not working:
http://www.dsl.sk/export/rss_articles.php
http://www.zive.sk/rss/najnovsie/
Instead of RSS digest, only last article or no article is received. Period of polling of listed feeds is 24h.

**To Reproduce**
goeland configuration, which is not working for listed RSS feeds, but it is working for 200+ other RSS feeds:

[sources]
[sources.src1]
url = "http://www.dsl.sk/export/rss_articles.php"
type = "feed"
filters = ["unseen", "includelink", "embedimage(left)", "digest(4)", "retrieve"]
[sources.src2]
url = "http://www.zive.sk/rss/najnovsie/"
type = "feed"
filters = ["unseen", "includelink", "embedimage(left)", "digest(4)", "retrieve"]

[pipes]
[pipes.src1]
source = "src1"
destination = "email"
email_to = "email@example.com"
email_from = "email@example.com"
email_title = "{{.EntryTitle}}"
[pipes.src2]
source = "src2"
destination = "email"
email_to = "email@example.com"
email_from = "email@example.com"
email_title = "{{.EntryTitle}}"

**Expected behavior**
Get the digest of all articles from last run.

**Screenshots**
N/A

**Additional context**

**Comment by slurdge** [comment] 2022-06-07 05:41
Thank you for the report. I'll look into it.

**Comment by slurdge** [comment] 2022-06-09 14:51
I think this is a duplicate of #38. Please try with version 0.10.3, as the two feeds you provided do not include UID for their article.

Also, I am curious about the 200+ feeds you have, would you mind sharing them so I can include them in a test ? Thanks.

**Comment by djm1** [comment] 2022-06-09 15:18
Hello,Thank you for your fast support - I have tested provided feeds and it is working :-) I will check tomorrow if the new feeds will be identified and let you know - tomorrow afternoon.For the other 200+ feeds - they are working fine without issue.Thank you for your great work to have this tool available :-)--S pozdravomMiroslav ***@***.***
-------- Original message --------From: slurdge ***@***.***> Date: 6/9/22  16:51  (GMT+01:00) To: slurdge/goeland ***@***.***> Cc: djm1 ***@***.***>, Author ***@***.***> Subject: Re: [slurdge/goeland] Digest of two RSS feeds not getting articles (Issue #41) 
I think this is a duplicate of #38. Please try with version 0.10.3, as the two feeds you provided do not include UID for their article.
Also, I am curious about the 200+ feeds you have, would you mind sharing them so I can include them in a test ? Thanks.

**Comment by slurdge** [comment] 2022-06-10 09:03
Duplicate of #38

**Closed as not planned by slurdge** 2022-06-10 09:03 UTC
Labels: duplicate

**Comment by djm1** [comment] 2022-10-11 07:20
Hello,Issue is solved, thank you again for quick support :-)--S pozdravomMiroslav ***@***.***
